# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Dependencia(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id: int=None, nombre: str=None):
        """
        Dependencia - a model defined in Swagger

        :param id: The id of this Dependencia.
        :type id: int
        :param nombre: The nombre of this Dependencia.
        :type nombre: str
        """
        self.swagger_types = {
            'id': int,
            'nombre': str
        }

        self.attribute_map = {
            'id': 'id',
            'nombre': 'nombre'
        }

        self._id = id
        self._nombre = nombre

    @classmethod
    def from_dict(cls, dikt) -> 'Dependencia':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Dependencia of this Dependencia.
        :rtype: Dependencia
        """
        return deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """
        Gets the id of this Dependencia.

        :return: The id of this Dependencia.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """
        Sets the id of this Dependencia.

        :param id: The id of this Dependencia.
        :type id: int
        """

        self._id = id

    @property
    def nombre(self) -> str:
        """
        Gets the nombre of this Dependencia.

        :return: The nombre of this Dependencia.
        :rtype: str
        """
        return self._nombre

    @nombre.setter
    def nombre(self, nombre: str):
        """
        Sets the nombre of this Dependencia.

        :param nombre: The nombre of this Dependencia.
        :type nombre: str
        """

        self._nombre = nombre

