version: '3'
services:
    mongo:
        build: ./mongo
    dependencia:
        build: ./dependencia
        depends_on:
            - mongo
        env_file: .config.env
    sala:
        build: ./sala
        depends_on:
            - mongo
        env_file: .config.env
    usuario:
        build: ./usuario
        depends_on:
            - mongo
            - dependencia
        env_file: .config.env
    apigw:
        build: ./apigw
        ports:
            - "80:8080"
        env_file: .config.env
        depends_on:
            - dependencia
            - usuario
