version: '3'
services:
    apigw:
        build: ./apigw
        ports:
            - "80:80"
    mongo:
        build: ./mongo
    dependencia:
        build: ./dependencia
        environment:
            - JWT_KEY=secret
            - DEBUG=True
            - DB_HOST=mongo
            - DB_NAME=salas
    swagger:
        image: swaggerapi/swagger-editor
