openapi: 3.0.0
info:
  description: Esta es la primera versión de la api del microservicio de Dependencia
  version: 1.0.0
  title: Dependencia
  contact:
    name: Jesus Flores
    email: joywarmgun@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: 'http://localhost/v1/dependencia/'
paths:
  /:
    get:
      tags:
        - Dependencia
      summary: Lista de dependencias
      description: Genera la lista completa de dependencias
      responses:
        '200':
          $ref: '#/components/responses/dependencias'
        '400':
          description: Datos inválidos
        '401':
          description: No autenticado
        '403':
          description: No autorizado
    post:
      tags:
        - Dependencia
      summary: Agrega una dependencia
      description: Agrega una dependencia si el perfil de usuario es Administrador
      requestBody:
        $ref: '#/components/requestBodies/propiedades'
      responses:
        '201':
          $ref: '#/components/schemas/Dependencia'
        '400':
          description: Datos inválidos
        '401':
          description: No autenticado
        '403':
          description: No autorizado
  '/{id}':
    get:
      tags:
        - Dependencia
      summary: Regresa una dependencia
      parameters: 
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          $ref: '#/components/schemas/Dependencia'
        '400':
          description: Datos inválidos
        '401':
          description: No autenticado
        '403':
          description: No autorizado
    put:
      tags:
        - Dependencia
      summary: Actualiza una dependencia
      description: Actualiza una dependencia si el usuario es Administrador
      parameters:
        - $ref: '#/components/parameters/id'
      requestBody:
        $ref: '#/components/requestBodies/propiedades'
      responses:
        '200':
          $ref: '#/components/schemas/Dependencia'
        '400':
          description: Datos inválidos
        '401':
          description: No autenticado
        '403':
          description: No autorizado
    delete:
      tags:
        - Dependencia
      summary: Elimina una dependencia
      description: >-
        Elimina una depenpendencia si el usuario es Administrador y no se ha
        usado para una reunión
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: Dependencia borrada
        '400':
          description: Datos inválidos
        '401':
          description: No autenticado
        '403':
          description: No autorizado
description: Dependencia no encontrada
security:
  - jwt: []
components:
  schemas:
    Dependencia:
      type: object
      properties:
        id:
          type: string
        nombre:
          type: string
  parameters:
    id:
      name: id
      in: path
      description: Id de la dependencia
      required: true
      schema:
        type: string
  requestBodies:
    propiedades:
      content:
        application/json:
          schema:
            type: object
            properties:
              nombre:
                type: string
  responses:
    dependencias:
      description: A complex object array response
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Dependencia'
  securitySchemes:
    jwt:
      type: apiKey
      name: token
      in: header
